apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Ashish\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: backend
    # io.kompose.service: backend
