apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Ashish\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    io.kompose.service: frontend
